services:
 live-solution:
  container_name: live-solution
  restart: unless-stopped
  image: node:20.10.0
  ports:
    - "4050:3005"
  volumes:
   - ./live-solution:/usr/src
  working_dir: /usr/src

  networks:
      - live-solution-network


    #PRODUCTION
  command: bash -c "npm install && npm run build && npm run start:prod:batch"


networks:
  live-solution-network:
    driver: bridge
